MKDB_v01/MKDB_v01/ViewModels/StoerungsbilderValidierenViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using MKDB_v01.Models;

namespace MKDB_v01.ViewModels
{
    

    

    public class ValidierenListViewModel
    {
        public IEnumerable<Stoerungsbild> Suchresultate { get; set; }
    }

    public class ValidierenViewModel
    {
        public Stoerungsbild Stoerungsbild { get; set; }

        [Display(Name = "Merkmale")]
        public int[] MerkmaleGesetztIds { get; set; }

        public IEnumerable<Merkmal> Merkmale { get; set; }
    }
}

    

MKDB_v01/MKDB_v01/Controllers/StoerungsbilderValidierenController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MKDB_v01.Models;
using MKDB_v01.ViewModels;

namespace MKDB_v01.Controllers
{
    [Authorize(Roles = "Superuser")]
    public class StoerungsbilderValidierenController : Controller
    {

        private ApplicationDbContext _context = new ApplicationDbContext();

        // GET: StoerungsbilderValidieren
        public ActionResult ValidierenList()
        {
            ValidierenListViewModel sbList = new ValidierenListViewModel();

            sbList.Suchresultate = _context.Stoerungsbilder
                .Include(s => s.Bauteil)
                .Include(s => s.Bauteil.Baugruppe)
                .Include(s => s.Merkmale)
                .Include(s => s.Bauteil.Fahrzeugtypen)
                .Where(s => s.IstNeu == true);



            return View(sbList);
        }


        public ActionResult Validieren(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ValidierenViewModel model = new ValidierenViewModel();

            model.Stoerungsbild = _context.Stoerungsbilder
                .Include(s => s.Bauteil)
                .Include(s => s.Bauteil.Fahrzeugtypen)
                .Include(s => s.Merkmale)
                .Include(s => s.Bauteil.Baugruppe)
                .Single(s => s.Id == id);

            if (model.Stoerungsbild == null)
            {
                return HttpNotFound();
            }

            model.Merkmale = _context.Merkmale;
            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Validieren(EditViewModel model)
        {
            Stoerungsbild sb = _context.Stoerungsbilder
                .Include(s => s.Bauteil)
                .Include(s => s.Bauteil.Fahrzeugtypen)
                .Include(s => s.Merkmale)
                .Include(s => s.Bauteil.Baugruppe)
                .Single(s => s.Id == model.Stoerungsbild.Id);

            sb.Stoerungstext = model.Stoerungsbild.Stoerungstext;
            sb.Beanstandung = model.Stoerungsbild.Beanstandung;
            sb.Abhilfe = model.Stoerungsbild.Abhilfe;
            sb.Ursache = model.Stoerungsbild.Ursache;

            //Gesetzte Merkmale aus der DB lesen und im Model Speichern
            if (model.MerkmaleGesetztIds != null)
            {
                sb.Merkmale = new List<Merkmal>();

                foreach (int i in model.MerkmaleGesetztIds)
                {
                    var mm = _context.Merkmale.Single(m => m.Id == i);

                    sb.Merkmale.Add(mm);
                }

            }

            //Validator setzen & Istneu entfernen
            sb.ValidationsDatum = DateTime.Today;
            sb.Validator = User.Identity.Name;

            sb.IstNeu = false;


            try
            {
                _context.Entry(sb).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("ValidierenList");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                
                ModelState.AddModelError("",
                    "Validation fehlgeschlagen, versuchen Sie es erneut und benachrichtigen Sie den Systemadministrator.");
                return View(model);
            }



        }

        

        public ActionResult Loeschen(int id)

        {
            Stoerungsbild stoerungsbild = _context.Stoerungsbilder
                .Include(s => s.Bauteil)
                .Include(s => s.Bauteil.Fahrzeugtypen)
                .Include(s => s.Merkmale)
                .Include(s => s.Bauteil.Baugruppe)
                .Single(s => s.Id == id);



            return View("Loeschen", stoerungsbild);
        }

        // POST: StoerungsbildSuchen/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult StoerungsbildLoeschen(Stoerungsbild sb)
        {
            try
            {
                Stoerungsbild stoerungsbild = _context.Stoerungsbilder.Find(sb.Id);
                _context.Stoerungsbilder.Remove(stoerungsbild);
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
            ModelState.AddModelError("", "Das Störungsbild wurde gelöscht");
            return RedirectToAction("ValidierenList");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }


}

MKDB_v01/MKDB_v01/Views/StoerungsbilderValidieren/Loeschen.cshtml
@model MKDB_v01.Models.Stoerungsbild

@{
    ViewBag.Title = "Löschen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Störungsbild löschen</h2>

<h3>Wollen Sie dieses Störungsbild wirklich löschen?</h3>
<div>
    <h4>Störungsbild</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Stoerungstext)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stoerungstext)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ErfassungsDatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ErfassungsDatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Erfasser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Erfasser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValidationsDatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValidationsDatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Validator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Validator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BauteilId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BauteilId)
        </dd>

    </dl>

    @using (Html.BeginForm("StoerungsbildLoeschen", "StoerungsbilderValidieren", Model))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-actions no-color">
            <input type="submit" value="Löschen" class="btn btn-primary" /> |
            <button onclick="goBack()" class="btn btn-link">Zurück zur Liste</button>
        </div>
    }
</div>



<script type="text/javascript">
    function goBack() {
        window.history.back();
    }
</script>

MKDB_v01/MKDB_v01/Views/StoerungsbilderValidieren/Validieren.cshtml
@model MKDB_v01.ViewModels.ValidierenViewModel


@{
    ViewBag.Title = "Stoerungsbild validieren";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}

<h2>Störungsbild validieren</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Überprüfen Sie die Angaben auf deren Korrektheit. </h4>
        <hr />
        <div>
            @Html.HiddenFor(model => model.Stoerungsbild.Id)
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Störungstext *", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stoerungsbild.Stoerungstext, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stoerungsbild.Stoerungstext, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Beanstandung *", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stoerungsbild.Beanstandung, new { htmlAttributes = new { @class = "form-control", @rows = 10 } })
                @Html.ValidationMessageFor(model => model.Stoerungsbild.Beanstandung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stoerungsbild.Ursache, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stoerungsbild.Ursache, new { htmlAttributes = new { @class = "form-control", @rows = 10 } })
                @Html.ValidationMessageFor(model => model.Stoerungsbild.Ursache, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stoerungsbild.Abhilfe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stoerungsbild.Abhilfe, new { htmlAttributes = new { @class = "form-control", @rows = 10 } })
                @Html.ValidationMessageFor(model => model.Stoerungsbild.Abhilfe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MerkmaleGesetztIds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(model => model.MerkmaleGesetztIds, new MultiSelectList(Model.Merkmale, "Id", "MerkmalName"),
                new { @class = "form-control", multiple = "multiple", id = "multiselect-merkmale" })
                @*@Html.ValidationMessageFor(model => model.MerkmaleGesetzt, "", new { @class = "text-danger" })*@
                
                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Validieren" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<p>
    <button onclick="goBack()" class="btn btn-link">Zurück zur Liste</button>
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    
}

<script src="~/Scripts/jquery-3.1.1.min.js"></script>

<script type="text/javascript">
    function goBack() {
        window.history.back();
    }


    $(document)
        .ready(function () {

            var myArray = [];
            @foreach (var d in Model.Stoerungsbild.Merkmale)
            {
                @:myArray.push("@d.Id");
            }
            
            $('#multiselect-merkmale').multiselect('select', myArray);

        });

    
   
</script>

MKDB_v01/MKDB_v01/Views/StoerungsbilderValidieren/ValidierenList.cshtml
@using Microsoft.Ajax.Utilities
@using System.Data.SqlClient


@model MKDB_v01.ViewModels.ValidierenListViewModel



@{
    ViewBag.Title = "Validieren";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Störungsbilder validieren</h2>

<h4>Hier sehen Sie alle nicht validierten Störungsbilder.</h4>
  

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Suchresultate.First().Stoerungstext)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Suchresultate.First().Bauteil.Baugruppe.BaugruppenName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Suchresultate.First().Bauteil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Suchresultate.First().Bauteil.Fahrzeugtypen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Suchresultate.First().ErfassungsDatum)
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model.Suchresultate)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Stoerungstext)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bauteil.Baugruppe.BaugruppenName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bauteil.BauteilName)
            </td>
            <td>
                @foreach (var ft in item.Bauteil.Fahrzeugtypen)
                {
                    <div>@Html.DisplayFor(ftItem => ft.FahrzeugtypName)</div>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ErfassungsDatum)
            </td>


            <td>



                <div>
                    @Html.ActionLink("Validieren", "Validieren", new { id = item.Id })
                </div>
                <div>
                    @Html.ActionLink(" Löschen", "Loeschen", new { id = item.Id })
                </div>



            </td>
        </tr>
    }

</table>


@if (!Model.Suchresultate.Any())
{
    <h4>Keine validierbaren Störungsbilder vorhanden!</h4>
}