MKDB_v01/MKDB_v01/ViewModels/StoerungsbildSuchenViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using MKDB_v01.Models;

namespace MKDB_v01.ViewModels
{
    public class SucheViewModel

    {

        [MaxLength(50, ErrorMessage = "\"{0}\" darf maximal {1} Zeichen besitzen.")]
        [Display(Name = "Freitext")]
        public string Freitext { get; set; }

        //----------------Dropdownfüllung-----------------
        public IEnumerable<Merkmal> Merkmale { get; set; }

        public IEnumerable<Fahrzeugtyp> Fahrzeugtypen { get; set; }

        public IEnumerable<Baugruppe> Baugruppen { get; set; }

        public IEnumerable<Bauteil> Bauteile { get; set; }

        //----------------Dropdown Resultate-----------------
        [Required(ErrorMessage = "Geben Sie mindestens einen Fahrzeugtypen an!")]
        [Display(Name = "Fahrzeugtypen *")]
        public int[] FahrzeugtypenGesetztIds { get; set; }

        [Display(Name = "Baugruppe")]
        public int? BaugruppeGesetztId { get; set; }

        [Display(Name = "Merkmale")]
        public int[] MerkmaleGesetztIds { get; set; }

        [Display(Name = "Bauteil")]
        public int? BauteilGesetztId { get; set; }



    }
    

    public class SuchresultateListViewModel
    {
        public IEnumerable<Stoerungsbild> Suchresultate { get; set; }   
    }

    public class EditViewModel
    {
        public Stoerungsbild Stoerungsbild { get; set; }

        [Display(Name = "Merkmale")]
        public int[] MerkmaleGesetztIds { get; set; }

        public IEnumerable<Merkmal> Merkmale { get; set; }
    }
}

MKDB_v01/MKDB_v01/Controllers/StoerungsbildSuchenController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using MKDB_v01.Models;
using MKDB_v01.ViewModels;

namespace MKDB_v01.Controllers
{
    public class StoerungsbildSuchenController : Controller
    {

        private readonly ApplicationDbContext _context = new ApplicationDbContext();

        // GET: StoerungsbildSuchen
        public ActionResult Suche()
        {
            var baugruppen = _context.Baugruppen.ToList();
            var fahrzeugtypen = _context.Fahrzeugtypen.ToList();
            var merkmale = _context.Merkmale.ToList();
            var bauteile = _context.Bauteile.ToList();

            var viewModel = new SucheViewModel()
            {
                Baugruppen = baugruppen,
                Fahrzeugtypen = fahrzeugtypen,
                Merkmale = merkmale,
                Bauteile = bauteile

            };
            return View(viewModel);
        }

        // GET: StoerungsbildSuchen/Details/5
        public ActionResult Details(int id)
        {
            try
            {


                Stoerungsbild stoerungsbild = _context.Stoerungsbilder
                    .Include(s => s.Bauteil)
                    .Include(s => s.Bauteil.Fahrzeugtypen)
                    .Include(s => s.Merkmale)
                    .Include(s => s.Bauteil.Baugruppe)
                    .Single(s => s.Id == id);

                return View("Details", stoerungsbild);

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                
                
                return View("Error");
            }

            
        }

        // GET: StoerungsbildSuchen/StoerungsbilderAusDbLesen
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult StoerungsbilderAusDbLesen(SucheViewModel model)
        {
            //_context = new ApplicationDbContext();
            // Minimal muss der Fahrzeugtyp angegeben werden
            if (!ModelState.IsValid)
            {
                model.Merkmale = _context.Merkmale.ToList();
                model.Baugruppen = _context.Baugruppen.ToList();
                model.Fahrzeugtypen = _context.Fahrzeugtypen.ToList();
                model.Bauteile = _context.Bauteile.ToList();
                    

                return View("Suche", model);
            }

            IEnumerable<Stoerungsbild> sb;

            if (model.BauteilGesetztId == 0 || model.BauteilGesetztId == null)
            {
                //holt alle störungsbilder aus der BD die einem der angegebenen Fahrzeugtypen zugeordnet sind
                sb = _context.Stoerungsbilder
                    .Include(s => s.Bauteil)
                    .Include(s => s.Bauteil.Baugruppe)
                    .Include(s => s.Merkmale)
                    .Include(s => s.Bauteil.Fahrzeugtypen)
                    .Where(
                        s =>
                            s.Bauteil.Fahrzeugtypen.Any(
                                l => s.IstNeu == false && model.FahrzeugtypenGesetztIds.Contains(l.Id))).ToList();
            }
            

            else
            {
                sb = _context.Stoerungsbilder
                    .Include(s => s.Bauteil)
                    .Include(s => s.Bauteil.Baugruppe)
                    .Include(s => s.Merkmale)
                    .Include(s => s.Bauteil.Fahrzeugtypen)
                    .Where(
                        s => s.IstNeu == false && s.Bauteil.Id == model.BauteilGesetztId).ToList();
            }
            
            
            if (model.Freitext != null)
            {
                sb = sb.Where(a => a.Stoerungstext.ToLower().Contains(model.Freitext.ToLower()) | a.Beanstandung.ToLower().Contains(model.Freitext.ToLower()));

            }
            
            if (model.BaugruppeGesetztId != null)
            {
                sb = sb.Where(a => a.Bauteil.Baugruppe.Id == model.BaugruppeGesetztId).ToList();

            }

            if (model.MerkmaleGesetztIds != null)
            {
                sb = sb.Where(s => s.Merkmale.Any(m => model.MerkmaleGesetztIds.Contains(m.Id))).ToList();


            }

            SuchresultateListViewModel returnModel = new SuchresultateListViewModel
            {
                Suchresultate = sb
            };


            return View("List", returnModel);
        }


        // GET: StoerungsbildSuchen/Edit/5
        [Authorize(Roles = "Superuser")]
        public ActionResult Edit(int id)
        {
            try
            {


                if (id == 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                EditViewModel model = new EditViewModel();

                model.Stoerungsbild = _context.Stoerungsbilder
                    .Include(s => s.Bauteil)
                    .Include(s => s.Bauteil.Fahrzeugtypen)
                    .Include(s => s.Merkmale)
                    .Include(s => s.Bauteil.Baugruppe)
                    .Single(s => s.Id == id);

                if (model.Stoerungsbild == null)
                {
                    return HttpNotFound();
                }

                model.Merkmale = _context.Merkmale;

                return View("Edit", model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);


                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Superuser")]
        public ActionResult Edit(EditViewModel model)
        {
            Stoerungsbild sb = _context.Stoerungsbilder
                .Include(s => s.Bauteil)
                .Include(s => s.Bauteil.Fahrzeugtypen)
                .Include(s => s.Merkmale)
                .Include(s => s.Bauteil.Baugruppe)
                .Single(s => s.Id == model.Stoerungsbild.Id);

            sb.Stoerungstext = model.Stoerungsbild.Stoerungstext;
            sb.Beanstandung = model.Stoerungsbild.Beanstandung;
            sb.Abhilfe = model.Stoerungsbild.Abhilfe;
            sb.Ursache = model.Stoerungsbild.Ursache;

            //Gesetzte Merkmale aus der DB lesen und im Model Speichern
            if (model.MerkmaleGesetztIds != null)
            {
                sb.Merkmale = new List<Merkmal>();

                foreach (int i in model.MerkmaleGesetztIds)
                {
                    var mm = _context.Merkmale.Single(m => m.Id == i);

                    sb.Merkmale.Add(mm);
                }

            }

            //Validator setzen & Istneu entfernen
            sb.ValidationsDatum = DateTime.Today;
            sb.Validator = User.Identity.Name;

            sb.IstNeu = false;


            try
            {
                _context.Entry(sb).State = EntityState.Modified;
                _context.SaveChanges();
                return View("Erfolg");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Edit fehlgeschlagen, versuchen Sie es erneut und benachrichtigen Sie den Systemadministrator.");
                return View("Edit", model);
            }



        }

        // GET: StoerungsbildSuchen/Delete/5
        [Authorize(Roles = "Superuser")]
        public ActionResult Loeschen(int id)


        {
            try
            {


                Stoerungsbild stoerungsbild = _context.Stoerungsbilder
                    .Include(s => s.Bauteil)
                    .Include(s => s.Bauteil.Fahrzeugtypen)
                    .Include(s => s.Merkmale)
                    .Include(s => s.Bauteil.Baugruppe)
                    .Single(s => s.Id == id);



                return View("Loeschen", stoerungsbild);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return View("Error");
            }
        }

        // POST: StoerungsbildSuchen/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Superuser")]
        public ActionResult StoerungsbildLoeschen(Stoerungsbild sb)
        {
            try
            {
                Stoerungsbild stoerungsbild = _context.Stoerungsbilder.Find(sb.Id);
                _context.Stoerungsbilder.Remove(stoerungsbild);
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return View("Error");
            }

            return View("Erfolg");
        }


        public JsonResult Bauteile(int? baugruppeId, int?[] fahrzeugtypenGesetztIds)  //Bauteile für das Dropdown aus der Datenbank laden
        {


            IEnumerable<Bauteil> bt =
                _context.Bauteile.Where(
                    b =>
                        b.Baugruppe.Id == baugruppeId &&
                        b.Fahrzeugtypen.Any(ft => fahrzeugtypenGesetztIds.Contains(ft.Id)));



            return Json(bt, JsonRequestBehavior.AllowGet); //Gibt die gefundenen Bauteile in einem Json zurück
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MKDB_v01/MKDB_v01/Views/StoerungsbildSuchen/Details.cshtml
@model MKDB_v01.Models.Stoerungsbild

@{
    ViewBag.Title = "Stoerungsbilderdetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Störungsbilderdetails</h2>

<div>
    <h4>Störungsbild</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Stoerungstext)
        </dt>
        <dd>
            @Html.DisplayTextFor(model => model.Stoerungstext)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bauteil)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bauteil.BauteilName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bauteil.Baugruppe)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bauteil.Baugruppe.BaugruppenName)
        </dd>
        <dd><hr /></dd>
        <dt>
            @Html.DisplayNameFor(model => model.Bauteil.Fahrzeugtypen)
        </dt>
        <dd>
        

            @foreach (var item in Model.Bauteil.Fahrzeugtypen)
            {
                <div>

                    @Html.DisplayFor(modelItem => item.FahrzeugtypName)
                    
                </div>
            }
        

        </dd>
        <dd><hr/></dd>
        <dt>
            @Html.DisplayNameFor(model => model.Beanstandung)
        </dt>
        <dd>
            @Html.DisplayTextFor(model => model.Beanstandung)
        </dd>
        <dd><hr /></dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ursache)
        </dt>
        <dd>
            @Html.DisplayTextFor(model => model.Ursache)
        </dd>
        <dd><hr /></dd>
        <dt>
            @Html.DisplayNameFor(model => model.Abhilfe)
        </dt>
        <dd>
            @Html.DisplayTextFor(model => model.Abhilfe)
        </dd>
        <dd><hr /></dd>
        <dt>
            @Html.DisplayNameFor(model => model.Erfasser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Erfasser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ErfassungsDatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ErfassungsDatum)
        </dd>

        @if (Model.ValidationsDatum.HasValue)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Validator)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Validator)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ValidationsDatum)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ValidationsDatum)
            </dd>

        }
        else
        {
            <dt>
                @Html.DisplayNameFor(model => model.Validator)
            </dt>
            <dd>
                ---
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ValidationsDatum)
            </dt>
            <dd>
                ---
            </dd>
        }
        <dd><hr /></dd>
        <dt>
            @Html.DisplayNameFor(model => model.Merkmale)
        </dt>

        <dd>
            

                @foreach (var item in Model.Merkmale)
                {
                    <div>
                        @Html.DisplayFor(modelItem => item.MerkmalName)
                    </div>
                }
            
        </dd>

    </dl>
</div>



<p>
    <button onclick="goBack()" class="btn btn-link">Zurück zur Liste</button>
</p>

<script type="text/javascript">
    function goBack() {
        window.history.back();
    }
</script>

MKDB_v01/MKDB_v01/Views/StoerungsbildSuchen/Edit.cshtml
@model MKDB_v01.ViewModels.EditViewModel


@{
    ViewBag.Title = "Stoerungsbild Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>Störungsbild Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Mit "*" markierte Felder sind erforderlich.</h4>
        <hr />
        <div>
            @Html.HiddenFor(model => model.Stoerungsbild.Id)
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Störungstext *", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stoerungsbild.Stoerungstext, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stoerungsbild.Stoerungstext, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Beanstandung *", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stoerungsbild.Beanstandung, new { htmlAttributes = new { @class = "form-control", @rows = 10 } })
                @Html.ValidationMessageFor(model => model.Stoerungsbild.Beanstandung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stoerungsbild.Ursache, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stoerungsbild.Ursache, new { htmlAttributes = new { @class = "form-control", @rows = 10 } })
                @Html.ValidationMessageFor(model => model.Stoerungsbild.Ursache, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stoerungsbild.Abhilfe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stoerungsbild.Abhilfe, new { htmlAttributes = new { @class = "form-control", @rows = 10 } })
                @Html.ValidationMessageFor(model => model.Stoerungsbild.Abhilfe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MerkmaleGesetztIds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(model => model.MerkmaleGesetztIds, new MultiSelectList(Model.Merkmale, "Id", "MerkmalName"),
                new { @class = "form-control", multiple = "multiple", id = "multiselect-merkmale" })
                @*@Html.ValidationMessageFor(model => model.MerkmaleGesetzt, "", new { @class = "text-danger" })*@


            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sichern" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<p>
    <button onclick="goBack()" class="btn btn-link">Zurück zur Liste</button>
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

<script src="~/Scripts/jquery-3.1.1.min.js"></script>

<script type="text/javascript">
    function goBack() {
        window.history.back();
    }


    $(document)
        .ready(function () {

            var myArray = [];
            @foreach (var d in Model.Stoerungsbild.Merkmale)
            {
                @:myArray.push("@d.Id");
            }

            $('#multiselect-merkmale').multiselect('select', myArray);

        });



</script>

MKDB_v01/MKDB_v01/Views/StoerungsbildSuchen/List.cshtml
@model MKDB_v01.ViewModels.SuchresultateListViewModel



@{
    ViewBag.Title = "Stoerungsbilder Liste";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Gefundene Störungsbilder</h2>

<h4></h4>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Suchresultate.First().Stoerungstext)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Suchresultate.First().Bauteil.Baugruppe.BaugruppenName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Suchresultate.First().Bauteil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Suchresultate.First().Bauteil.Fahrzeugtypen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Suchresultate.First().ErfassungsDatum)
        </th>
        
        
        <th></th>
    </tr>
   

    @foreach (var item in Model.Suchresultate) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Stoerungstext)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bauteil.Baugruppe.BaugruppenName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bauteil.BauteilName)
            </td>
            <td>
                @foreach (var ft in item.Bauteil.Fahrzeugtypen)
                {
                    <div>@Html.DisplayFor(ftItem => ft.FahrzeugtypName)</div>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ErfassungsDatum)
            </td>
            
        
            <td>
                @Html.ActionLink(" Details", "Details", new { id = item.Id })
                

                @if (User.IsInRole("Superuser"))

                {
                    <div>
                        @Html.ActionLink("Edit", "Edit", new {id = item.Id})
                    </div>
                    <div>
                        @Html.ActionLink(" Löschen", "Loeschen", new {id = item.Id})
                    </div>

                }
                

            </td>
        </tr>
    }

</table>

@if (!Model.Suchresultate.Any())
{
    <h4>Keine passenden Störungsbilder vorhanden!</h4>
}

MKDB_v01/MKDB_v01/Views/StoerungsbildSuchen/Loeschen.cshtml
@model MKDB_v01.Models.Stoerungsbild

@{
    ViewBag.Title = "Löschen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Störungsbild löschen</h2>

<h3>Wollen Sie dieses Störungsbild wirklich löschen?</h3>
<div>
    <h4>Störungsbild</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Stoerungstext)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stoerungstext)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ErfassungsDatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ErfassungsDatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Erfasser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Erfasser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValidationsDatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValidationsDatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Validator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Validator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BauteilId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BauteilId)
        </dd>

    </dl>

    @using (Html.BeginForm("StoerungsbildLoeschen", "StoerungsbildSuchen", Model))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-actions no-color">
            <input type="submit" value="Löschen" class="btn btn-primary" /> |
            <button onclick="goBack()" class="btn btn-link">Zurück zur Liste</button>
        </div>
    }
</div>



<script type="text/javascript">
    function goBack() {
        window.history.back();
    }
</script>

MKDB_v01/MKDB_v01/Views/StoerungsbildSuchen/Suche.cshtml
@using System.Data.SqlClient

@model MKDB_v01.ViewModels.SucheViewModel

@{
    ViewBag.Title = "Suchen";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>Störungsbild suchen</h2>

@using (Html.BeginForm("StoerungsbilderAusDbLesen", "StoerungsbildSuchen"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h4>Geben Sie mindestens einen Fahrzeugtypen an.</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })

        <div class="form-group">
            
                @Html.LabelFor(model => model.FahrzeugtypenGesetztIds, htmlAttributes: new { @class = "control-label col-md-2" })
            
            <div class="col-md-10">

                @Html.DropDownListFor(model => model.FahrzeugtypenGesetztIds, new MultiSelectList(Model.Fahrzeugtypen, "Id", "FahrzeugtypName"),
                    new { @class = "multiselect form-control", multiple = "multiple", id = "multiselect-fahrzeugtypen" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Freitext, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Freitext, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.Stoerungstext, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BaugruppeGesetztId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.BaugruppeGesetztId,
                    new SelectList(Model.Baugruppen, "Id", "BaugruppenName"), "Baugruppe wählen", new
                    {
                        @class = "form-control",
                        id = "dropdown-baugruppen"
                    })
                @*@Html.ValidationMessageFor(model => model.BaugruppeGesetztId, "", new {@class = "text-danger"})*@
            </div>
        </div>



        <div class="form-group">

            @Html.LabelFor(model => model.BauteilGesetztId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => Model.BauteilGesetztId, new SelectList("", ""), "Bauteil wählen",
                    new { @class = "form-control", id = "select-bauteile" })


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MerkmaleGesetztIds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(model => model.MerkmaleGesetztIds, new MultiSelectList(Model.Merkmale, "Id", "MerkmalName"),
                new { @class = "form-control", multiple = "multiple", id = "multiselect-merkmale" })
                @*@Html.ValidationMessageFor(model => model.MerkmaleGesetzt, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Suchen" class="btn btn-primary" />
            </div>
        </div>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

<script src="~/Scripts/jquery-3.1.1.min.js"></script>



<!-- Multiselect Plugin initialisieren: -->
<script type="text/javascript">

    var gesetzteFahrzeugtypen;
    var gesetzteBaugruppe;

    $(document).ready(function () {

        gesetzteFahrzeugtypen = $('#multiselect-fahrzeugtypen').val();
        gesetzteBaugruppe = $('#dropdown-baugruppen').val();
        bauteileLaden();

        $('#multiselect-fahrzeugtypen').multiselect({
            includeSelectAllOption: true,
            selectAllText: 'Alle wählen',
            onDropdownHide: function (event) {

                gesetzteFahrzeugtypen = $('#multiselect-fahrzeugtypen').val();
                $('#select-bauteile').multiselect('dataprovider', []);
                bauteileLaden();
            }
        });

        $("#dropdown-baugruppen").multiselect({
            onDropdownHide: function (event) {

                gesetzteBaugruppe = $('#dropdown-baugruppen').val();
                $('#select-bauteile').multiselect('dataprovider', []);
                bauteileLaden();

            }
        });


        $("#multiselect-merkmale").multiselect();

        $('#select-bauteile').multiselect({
            enableFiltering: true,
            disableIfEmpty: true
        });
    });


    var bauteileLaden = function () {

        if (jQuery.isEmptyObject(gesetzteBaugruppe) | jQuery.isEmptyObject(gesetzteFahrzeugtypen)) {
            return;
        }


        $('#select-bauteile').multiselect('dataprovider', []);


        jQuery.post(
            '../StoerungsbildSuchen/Bauteile',
            {
                baugruppeId: gesetzteBaugruppe,
                fahrzeugtypenGesetztIds: gesetzteFahrzeugtypen


            },
            function (data) {
                var result = data;

                var bauteileOptionList = []; bauteileOptionList.push({
                    'label': 'Bauteil wählen',
                    'value': '0'
                });
                jQuery.each(result, function (i, item) {
                    bauteileOptionList.push({
                        'label': item['BauteilName'],
                        'value': item['Id']
                    });

                });

                jQuery('#select-bauteile').multiselect('dataprovider', bauteileOptionList);

            });
    }

</script>