MKDB_v01/MKDB_v01/ViewModels/StoerungsbildErfassenViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using MKDB_v01.Models;

namespace MKDB_v01.ViewModels
{
    public class ErfassenViewModel

    {
        //----------------Dropdownfüllung-----------------
        public IEnumerable<Merkmal> Merkmale { get; set; }

        [Display(Name = "Fahrzeugtypen *")]
        public IEnumerable<Fahrzeugtyp> Fahrzeugtypen { get; set; }

        [Display(Name = "Baugruppe *")]
        public IEnumerable<Baugruppe> Baugruppen { get; set; }

        [Display(Name = "Bauteil *")]
        public IEnumerable<Bauteil> Bauteile { get; set; }

        //----------------Dropdown Resultate-----------------
        
        [Display (Name = "Fahrzeugtypen *")]
        public int[] FahrzeugtypenGesetztIds { get; set; }
        
        [Display(Name = "Merkmale")]
        public int[] MerkmaleGesetztIds { get; set; }
        
        //----------------Name des, zu erstellenden, Bauteils-----------------
        [MaxLength(50, ErrorMessage = "\"{0}\" darf maximal {1} Zeichen besitzen.")]
        [Display(Name = "Neues Bauteil *")]
        public string NeuesBauteil { get; set; }
        
        public Stoerungsbild Stoerungsbild { get; set; }
    }
}
 

MKDB_v01/MKDB_v01/Controllers/StoerungsbildErfassenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using MKDB_v01.Models;
using MKDB_v01.ViewModels;

namespace MKDB_v01.Controllers
{
    [Authorize(Roles = "Superuser,Writer")]
    public class StoerungsbildErfassenController : Controller
    {
        private readonly ApplicationDbContext _context = new ApplicationDbContext();

        // GET: StörungsbildErfassen
        public ActionResult Erfassen()
        {
            var baugruppen = _context.Baugruppen.ToList();
            var fahrzeugtypen = _context.Fahrzeugtypen.ToList();
            var merkmale = _context.Merkmale.ToList();
            var bauteile = _context.Bauteile.ToList();

            var viewModel = new ErfassenViewModel
            {
                Baugruppen = baugruppen,
                Fahrzeugtypen = fahrzeugtypen,
                Merkmale = merkmale,
                Bauteile = bauteile
            };

            ViewBag.var3 = bauteile;

            return View(viewModel);
        }


        // POST: StörungsbildErfassen/Erfassen
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> StoerungsbildInDbSchreiben(ErfassenViewModel model)
        {
            ModelState["Stoerungsbild.Erfasser"].Errors.Clear();

            if (((model.Stoerungsbild.BauteilId != null) && (model.Stoerungsbild.BauteilId != 0)) ||
                (model.NeuesBauteil != null))
                ModelState["Stoerungsbild.Bauteil.BauteilName"].Errors.Clear();

            if (!((model.Stoerungsbild.BauteilId == null) || (model.Stoerungsbild.BauteilId == 0)) &&
                (model.NeuesBauteil != null))
                ModelState.AddModelError("error",
                    "Es wurde ein neues Bauteil und ein bestehendes Bauteil angegeben. Bitte nur eine Funktion verwenden!");


            if (model.FahrzeugtypenGesetztIds != null)
                ModelState["Stoerungsbild.Bauteil.Fahrzeugtypen"].Errors.Clear();
            if (model.Stoerungsbild.Bauteil.BaugruppeId != 0)
                ModelState["Stoerungsbild.Bauteil.Baugruppe"].Errors.Clear();

            //--------------------->> Validierung für nur ein Bauteil fehlt noch

            if (!ModelState.IsValid)
            {
                model.Merkmale = _context.Merkmale.ToList();
                model.Baugruppen = _context.Baugruppen.ToList();
                model.Fahrzeugtypen = _context.Fahrzeugtypen.ToList();
                model.Bauteile = _context.Bauteile.ToList();
                model.Stoerungsbild.BauteilId = 0;

                return View("Erfassen", model);
            }


            model.Stoerungsbild.Erfasser = User.Identity.Name;
            model.Stoerungsbild.ErfassungsDatum = DateTime.Today;

            // wenn der User Supeuser ist, wird er als Validator angegeben
            if (User.IsInRole("Superuser"))
            {
                model.Stoerungsbild.IstNeu = false;
                model.Stoerungsbild.Validator = User.Identity.Name;
                model.Stoerungsbild.ValidationsDatum = DateTime.Today;
            }
            // Reader wird das Störungsbild als neu markiert
            else
            {
                model.Stoerungsbild.IstNeu = true;
            }

            //wenn ein neues Bauteil angegeben wurde, wird dieses erst erstellt
            if (model.NeuesBauteil != null)
            {
                model.Stoerungsbild.Bauteil.Fahrzeugtypen = new List<Fahrzeugtyp>();

                foreach (var i in model.FahrzeugtypenGesetztIds)
                {
                    var typ = _context.Fahrzeugtypen.Single(f => f.Id == i);

                    model.Stoerungsbild.Bauteil.Fahrzeugtypen.Add(typ);
                }

                model.Stoerungsbild.Bauteil.Baugruppe =
                    _context.Baugruppen.Single(b => b.Id == model.Stoerungsbild.Bauteil.BaugruppeId);

                model.Stoerungsbild.Bauteil.BauteilName = model.NeuesBauteil;

                //Neues Bauteil wird in die DB geschrieben
                _context.Bauteile.Add(model.Stoerungsbild.Bauteil);
                //await _context.SaveChangesAsync();
            }

            //wenn kein neues Bauteil angegeben wurde, wird es aus der DB geladen
            else if ((model.NeuesBauteil == null) &&
                     ((model.Stoerungsbild.BauteilId != null) & (model.Stoerungsbild.BauteilId != 0)))
            {
                model.Stoerungsbild.Bauteil = _context.Bauteile.Single(b => b.Id == model.Stoerungsbild.BauteilId);
            }


            // Merkmale hinzufügen
            if (model.MerkmaleGesetztIds != null)
            {
                model.Stoerungsbild.Merkmale = new List<Merkmal>();

                foreach (var i in model.MerkmaleGesetztIds)
                {
                    var mm = _context.Merkmale.Single(m => m.Id == i);

                    model.Stoerungsbild.Merkmale.Add(mm);
                }
            }

            try
            {
                _context.Stoerungsbilder.Add(model.Stoerungsbild);
                await _context.SaveChangesAsync();

                return View("Erfolg");
            }
            // irgendwas ist schiefgegangen
            catch (Exception e)
            {
                Console.WriteLine(e);
                return View("Fehlgeschlagen");
            }
        }

        public JsonResult Bauteile(int? baugruppeId, int?[] fahrzeugtypenGesetztIds)
            //fetch the team details from database
        {
            

            IEnumerable<Bauteil> bt =
                _context.Bauteile.Where(
                    b =>
                        (b.Baugruppe.Id == baugruppeId) &&
                        b.Fahrzeugtypen.Any(ft => fahrzeugtypenGesetztIds.Contains(ft.Id)));


            return Json(bt, JsonRequestBehavior.AllowGet); //return the list objects in json form
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _context.Dispose();
            base.Dispose(disposing);
        }
    }
}

MKDB_v01/MKDB_v01/Views/StoerungsbildErfassen/Erfassen.cshtml
@using System.Data.SqlClient
@using MKDB_v01.Models

<script src="/Scripts/modernizr-2.8.3.js" type="text/javascript"></script>
<script src="/Scripts/jquery-3.1.1.min.js" type="text/javascript"></script>


@model MKDB_v01.ViewModels.ErfassenViewModel

@{
    ViewBag.Title = "Erfassen";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>Störungsbild erfassen</h2>


@using (Html.BeginForm("StoerungsbildInDbSchreiben", "StoerungsbildErfassen"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Mit "*" markierte Felder sind erforderlich.</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.FahrzeugtypenGesetztIds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(model => model.FahrzeugtypenGesetztIds, new MultiSelectList(Model.Fahrzeugtypen, "Id", "FahrzeugtypName"),
                    new { @class = "multiselect form-control", multiple = "multiple", id = "multiselect-fahrzeugtypen" })

            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Baugruppen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Stoerungsbild.Bauteil.BaugruppeId,
                    new SelectList(Model.Baugruppen, "Id", "BaugruppenName"), "Baugruppe wählen", new
                    {
                        @class = "form-control",
                        id = "dropdown-baugruppen"

                    })

            </div>
        </div>

        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">

                <div class="btn-group" id="accordion">
                    <button class="btn btn-primary" type="button" id="butnOne" data-toggle="collapse" data-parent="#accordion"
                            href="#collapseOne" aria-expanded="false" aria-controls="collapseOne" onclick="closeTwo()">
                        Bestehendes Bauteil
                    </button>
                    <button class="btn btn-primary" type="button" id="butnTwo" data-toggle="collapse" data-parent="#accordion"
                            href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" onclick="closeOne()">
                        Neues Bauteil
                    </button>

                </div>
                @Html.ValidationMessageFor(model => model.Stoerungsbild.Bauteil.Baugruppe, "", new { @class = "text-danger" })
            </div>
        </div>


        <div id="collapseOne" class="form-group collapse" aria-labelledby="headingOne">

            @Html.LabelFor(model => model.Bauteile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => Model.Stoerungsbild.BauteilId, new SelectList("", ""), "Bauteil wählen",
                    new { @class = "form-control", id = "select-bauteile" })


            </div>
        </div>


        <div id="collapseTwo" class="form-group collapse" aria-labelledby="headingOne">

            @Html.LabelFor(model => model.NeuesBauteil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NeuesBauteil, new { htmlAttributes = new { @class = "form-control", id = "neue-bauteile" } })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Störungstext *", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stoerungsbild.Stoerungstext, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.Stoerungstext, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Beanstandung *", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" , aria-expanded="true">
                @Html.EditorFor(model => model.Stoerungsbild.Beanstandung, new { htmlAttributes = new { @class = "form-control", @rows = 10 } })
                @*@Html.ValidationMessageFor(model => model.Beanstandung, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stoerungsbild.Ursache, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stoerungsbild.Ursache, new { htmlAttributes = new { @class = "form-control", @rows = 10 } })
                @*@Html.ValidationMessageFor(model => model.Ursache, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stoerungsbild.Abhilfe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stoerungsbild.Abhilfe, new { htmlAttributes = new { @class = "form-control", @rows = 10 } })
                @*@Html.ValidationMessageFor(model => model.Abhilfe, "", new { @class = "text-danger" })*@
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MerkmaleGesetztIds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(model => model.MerkmaleGesetztIds, new SelectList(Model.Merkmale, "Id", "MerkmalName"),
                new { @class = "form-control", multiple = "multiple", id = "multiselect-merkmale" })
                @*@Html.ValidationMessageFor(model => model.MerkmaleGesetzt, "", new { @class = "text-danger" })*@
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Erfassen" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

<script src="~/Scripts/jquery-3.1.1.min.js"></script>



<!-- Multiselect Plugin initialisieren: -->
<script type="text/javascript">

    function closeTwo() {
        $('#collapseOne').collapse('show');
        $('#collapseTwo').collapse('hide');
        
    }
    function closeOne() {
        $('#collapseTwo').collapse('show');
        $('#collapseOne').collapse('hide');
        
    }


    var gesetzteFahrzeugtypen;
    var gesetzteBaugruppe;

    $(document).ready(function () {

        gesetzteFahrzeugtypen = $('#multiselect-fahrzeugtypen').val();
        gesetzteBaugruppe = $('#dropdown-baugruppen').val();
        bauteileLaden();

        $('#multiselect-fahrzeugtypen').multiselect({
            includeSelectAllOption: true,
            selectAllText: 'Alle wählen',
            onDropdownHide: function (event) {

                gesetzteFahrzeugtypen = $('#multiselect-fahrzeugtypen').val();
                $('#select-bauteile').multiselect('dataprovider', []);
                bauteileLaden();
            }
        });

        $("#dropdown-baugruppen").multiselect({
            onDropdownHide: function (event) {

                gesetzteBaugruppe = $('#dropdown-baugruppen').val();
                $('#select-bauteile').multiselect('dataprovider', []);
                bauteileLaden();

            }
        });


        $("#multiselect-merkmale").multiselect();

        $('#select-bauteile').multiselect({
            enableFiltering: true,
            disableIfEmpty: true
        });
    });


    var bauteileLaden = function () {

        if (jQuery.isEmptyObject(gesetzteBaugruppe) | jQuery.isEmptyObject(gesetzteFahrzeugtypen)) {
            return;
        }


        $('#select-bauteile').multiselect('dataprovider', []);


        jQuery.post(
            '../StoerungsbildSuchen/Bauteile',
            {
                baugruppeId: gesetzteBaugruppe,
                fahrzeugtypenGesetztIds: gesetzteFahrzeugtypen


            },
            function (data) {
                var result = data;

                var bauteileOptionList = []; bauteileOptionList.push({
                    'label': 'Bauteil wählen',
                    'value': '0'
                });
                jQuery.each(result, function (i, item) {
                    bauteileOptionList.push({
                        'label': item['BauteilName'],
                        'value': item['Id']
                    });

                });

                jQuery('#select-bauteile').multiselect('dataprovider', bauteileOptionList);

            });
    }


    


</script>